package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// installerVersion is embedded in generated scripts for diagnostics.
const installerVersion = "0.1"

// installerShellTemplate is the shell script header that gets prepended to the
// base64 payload. It is a text/template with the following variables:
//   - .ExtensionName  — the PostgreSQL extension name (e.g. "myext")
//   - .Version        — the extension version string (e.g. "0.1")
var installerShellTemplate = template.Must(template.New("installer").Parse(`#!/bin/sh
# Self-contained installer for the "{{.ExtensionName}}" PostgreSQL extension.
# Generated by plgo — https://gitlab.com/microo8/plgo
#
# Usage:
#   sudo ./install-{{.ExtensionName}}.sh [OPTIONS]
#
# Options:
#   --create-extension   After installing files, run CREATE EXTENSION via psql
#   --db DATABASE        Database for CREATE EXTENSION (default: postgres)
#   --pg-config PATH     Path to pg_config (default: auto-detect)
#   --uninstall          Remove the extension files and optionally DROP EXTENSION
#   --dry-run            Show what would be done without changing anything
#   --help               Show this help message
#
# Environment:
#   PG_CONFIG            Same as --pg-config
#   PGDATABASE           Same as --db
set -e

EXTENSION="{{.ExtensionName}}"
VERSION="{{.Version}}"
SO_FILE="${EXTENSION}.so"
SQL_FILE="${EXTENSION}--${VERSION}.sql"
CONTROL_FILE="${EXTENSION}.control"

# --- Defaults ---
CREATE_EXT=false
UNINSTALL=false
DRY_RUN=false
DB="${PGDATABASE:-postgres}"
PGCONFIG="${PG_CONFIG:-}"

# --- Colors (disabled if not a terminal) ---
if [ -t 1 ]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; NC=''
fi

info()  { printf "${GREEN}==>${NC} ${BOLD}%s${NC}\n" "$*"; }
warn()  { printf "${YELLOW}==> WARNING:${NC} %s\n" "$*"; }
error() { printf "${RED}==> ERROR:${NC} %s\n" "$*" >&2; }
die()   { error "$*"; exit 1; }

# --- Parse arguments ---
while [ $# -gt 0 ]; do
    case "$1" in
        --create-extension) CREATE_EXT=true ;;
        --db)               DB="$2"; shift ;;
        --db=*)             DB="${1#--db=}" ;;
        --pg-config)        PGCONFIG="$2"; shift ;;
        --pg-config=*)      PGCONFIG="${1#--pg-config=}" ;;
        --uninstall)        UNINSTALL=true ;;
        --dry-run)          DRY_RUN=true ;;
        --help|-h)
            sed -n '2,/^set -e/{ /^#/s/^# \{0,1\}//p }' "$0"
            exit 0
            ;;
        *) die "Unknown option: $1 (try --help)" ;;
    esac
    shift
done

# --- Locate pg_config ---
find_pg_config() {
    # 1. Explicit path
    if [ -n "$PGCONFIG" ]; then
        if [ -x "$PGCONFIG" ]; then
            echo "$PGCONFIG"
            return
        fi
        die "pg_config not found at: $PGCONFIG"
    fi

    # 2. $PATH
    if command -v pg_config >/dev/null 2>&1; then
        command -v pg_config
        return
    fi

    # 3. Common install locations
    for dir in \
        /usr/lib/postgresql/*/bin \
        /usr/pgsql-*/bin \
        /usr/local/pgsql/bin \
        /opt/homebrew/opt/postgresql@*/bin \
        /opt/homebrew/bin \
        /Library/PostgreSQL/*/bin; do
        # shellcheck disable=SC2086
        for candidate in $dir/pg_config; do
            if [ -x "$candidate" ]; then
                echo "$candidate"
                return
            fi
        done
    done

    die "pg_config not found. Install postgresql-server-dev or use --pg-config /path/to/pg_config"
}

PGCONFIG="$(find_pg_config)"
info "Using pg_config: $PGCONFIG"

PG_VERSION="$("$PGCONFIG" --version)"
SHAREDIR="$("$PGCONFIG" --sharedir)"
PKGLIBDIR="$("$PGCONFIG" --pkglibdir)"
EXTDIR="${SHAREDIR}/extension"

info "PostgreSQL: ${PG_VERSION}"
info "Extension dir: ${EXTDIR}"
info "Library dir:   ${PKGLIBDIR}"

# --- Extract payload to temp dir ---
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

extract_payload() {
    local marker="__PAYLOAD_BELOW__"
    local payload_start
    payload_start="$(grep -n "^${marker}$" "$0" | tail -1 | cut -d: -f1)"
    if [ -z "$payload_start" ]; then
        die "Corrupt installer: payload marker not found"
    fi
    payload_start=$((payload_start + 1))

    # The payload is three base64-encoded sections separated by marker lines:
    #   __CONTROL__
    #   <base64 of .control file>
    #   __SQL__
    #   <base64 of .sql file>
    #   __SO__
    #   <base64 of .so file>
    local current_section=""
    tail -n +"$payload_start" "$0" | while IFS= read -r line; do
        case "$line" in
            __CONTROL__) current_section="control" ;;
            __SQL__)     current_section="sql" ;;
            __SO__)      current_section="so" ;;
            *)
                case "$current_section" in
                    control) echo "$line" >> "${TMPDIR}/control.b64" ;;
                    sql)     echo "$line" >> "${TMPDIR}/sql.b64" ;;
                    so)      echo "$line" >> "${TMPDIR}/so.b64" ;;
                esac
                ;;
        esac
    done

    base64 -d < "${TMPDIR}/control.b64" > "${TMPDIR}/${CONTROL_FILE}"
    base64 -d < "${TMPDIR}/sql.b64"     > "${TMPDIR}/${SQL_FILE}"
    base64 -d < "${TMPDIR}/so.b64"      > "${TMPDIR}/${SO_FILE}"
}

extract_payload

# --- Uninstall mode ---
if [ "$UNINSTALL" = true ]; then
    info "Uninstalling ${EXTENSION}..."
    if [ "$DRY_RUN" = true ]; then
        echo "  Would remove: ${EXTDIR}/${CONTROL_FILE}"
        echo "  Would remove: ${EXTDIR}/${SQL_FILE}"
        echo "  Would remove: ${PKGLIBDIR}/${SO_FILE}"
        if [ "$CREATE_EXT" = true ]; then
            echo "  Would run: DROP EXTENSION IF EXISTS ${EXTENSION} CASCADE"
        fi
        info "Dry run complete — no changes made."
        exit 0
    fi

    if [ "$CREATE_EXT" = true ]; then
        PSQL="$(dirname "$PGCONFIG")/psql"
        if [ -x "$PSQL" ]; then
            info "Dropping extension from database '${DB}'..."
            "$PSQL" -d "$DB" -c "DROP EXTENSION IF EXISTS ${EXTENSION} CASCADE;" || warn "DROP EXTENSION failed (maybe it wasn't loaded)"
        else
            warn "psql not found — skip DROP EXTENSION"
        fi
    fi

    rm -f "${EXTDIR}/${CONTROL_FILE}" "${EXTDIR}/${SQL_FILE}" "${PKGLIBDIR}/${SO_FILE}"
    info "${EXTENSION} uninstalled successfully."
    exit 0
fi

# --- Check for existing installation ---
if [ -f "${PKGLIBDIR}/${SO_FILE}" ] && [ "$DRY_RUN" = false ]; then
    warn "Existing ${SO_FILE} found in ${PKGLIBDIR} — will be overwritten."
fi

# --- Install files ---
if [ "$DRY_RUN" = true ]; then
    info "Dry run — would install:"
    echo "  ${TMPDIR}/${CONTROL_FILE}  →  ${EXTDIR}/${CONTROL_FILE}"
    echo "  ${TMPDIR}/${SQL_FILE}      →  ${EXTDIR}/${SQL_FILE}"
    echo "  ${TMPDIR}/${SO_FILE}       →  ${PKGLIBDIR}/${SO_FILE}"
    if [ "$CREATE_EXT" = true ]; then
        echo "  Would run: CREATE EXTENSION IF NOT EXISTS ${EXTENSION}"
    fi
    info "Dry run complete — no changes made."
    exit 0
fi

info "Installing ${EXTENSION} v${VERSION}..."

install -d "${EXTDIR}"
install -m 644 "${TMPDIR}/${CONTROL_FILE}" "${EXTDIR}/${CONTROL_FILE}"
install -m 644 "${TMPDIR}/${SQL_FILE}"     "${EXTDIR}/${SQL_FILE}"
install -d "${PKGLIBDIR}"
install -m 755 "${TMPDIR}/${SO_FILE}"      "${PKGLIBDIR}/${SO_FILE}"

info "Files installed:"
echo "  ${EXTDIR}/${CONTROL_FILE}"
echo "  ${EXTDIR}/${SQL_FILE}"
echo "  ${PKGLIBDIR}/${SO_FILE}"

# --- Optional: CREATE EXTENSION ---
if [ "$CREATE_EXT" = true ]; then
    PSQL="$(dirname "$PGCONFIG")/psql"
    if [ ! -x "$PSQL" ]; then
        # Try PATH
        if command -v psql >/dev/null 2>&1; then
            PSQL="psql"
        else
            warn "psql not found — skipping CREATE EXTENSION."
            warn "Run manually:  psql -d ${DB} -c \"CREATE EXTENSION IF NOT EXISTS ${EXTENSION};\""
            exit 0
        fi
    fi
    info "Creating extension in database '${DB}'..."
    "$PSQL" -d "$DB" -c "CREATE EXTENSION IF NOT EXISTS ${EXTENSION};"
    info "Extension '${EXTENSION}' is ready to use!"
else
    echo ""
    info "Installation complete. To activate the extension, run:"
    printf "  ${BLUE}psql -d <yourdb> -c \"CREATE EXTENSION ${EXTENSION};\"${NC}\n"
fi

exit 0
__PAYLOAD_BELOW__
`))

// installerData holds the template variables for the shell script.
type installerData struct {
	ExtensionName string
	Version       string
}

// WriteInstaller generates a self-contained .sh installer script.
// It embeds the compiled .so, the SQL file, and the .control file as
// base64-encoded payload sections after the shell script header.
//
// buildDir is the path to the build/ directory containing the artifacts.
// outPath is the output .sh file path (e.g. "install-myext.sh").
func (mw *ModuleWriter) WriteInstaller(buildDir, outPath string) error {
	version := "0.1"

	// Read the three artifacts from the build directory
	soData, err := os.ReadFile(filepath.Join(buildDir, mw.PackageName+".so"))
	if err != nil {
		return fmt.Errorf("read .so: %w", err)
	}

	sqlData, err := os.ReadFile(filepath.Join(buildDir, mw.PackageName+"--"+version+".sql"))
	if err != nil {
		return fmt.Errorf("read .sql: %w", err)
	}

	controlData, err := os.ReadFile(filepath.Join(buildDir, mw.PackageName+".control"))
	if err != nil {
		return fmt.Errorf("read .control: %w", err)
	}

	// Render the shell script header
	var header bytes.Buffer
	err = installerShellTemplate.Execute(&header, installerData{
		ExtensionName: mw.PackageName,
		Version:       version,
	})
	if err != nil {
		return fmt.Errorf("render template: %w", err)
	}

	// Build the payload: three base64 sections
	var payload bytes.Buffer
	payload.WriteString("__CONTROL__\n")
	payload.WriteString(base64Encode(controlData))
	payload.WriteString("\n__SQL__\n")
	payload.WriteString(base64Encode(sqlData))
	payload.WriteString("\n__SO__\n")
	payload.WriteString(base64Encode(soData))
	payload.WriteString("\n")

	// Write header + payload to output file
	outFile, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create installer: %w", err)
	}
	defer outFile.Close()

	if _, err := outFile.Write(header.Bytes()); err != nil {
		return fmt.Errorf("write header: %w", err)
	}
	if _, err := outFile.Write(payload.Bytes()); err != nil {
		return fmt.Errorf("write payload: %w", err)
	}

	// Make executable
	if err := outFile.Chmod(0o755); err != nil {
		return fmt.Errorf("chmod: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Installer written to: %s (%s)\n", outPath, humanSize(header.Len()+payload.Len()))
	return nil
}

// base64Encode encodes data to base64 with line wrapping at 76 chars
// (standard MIME line length, compatible with all base64 decoders).
func base64Encode(data []byte) string {
	encoded := base64.StdEncoding.EncodeToString(data)
	// Wrap at 76 characters
	var wrapped bytes.Buffer
	for i := 0; i < len(encoded); i += 76 {
		end := i + 76
		if end > len(encoded) {
			end = len(encoded)
		}
		wrapped.WriteString(encoded[i:end])
		if end < len(encoded) {
			wrapped.WriteByte('\n')
		}
	}
	return wrapped.String()
}

// humanSize returns a human-readable file size.
func humanSize(bytes int) string {
	const (
		KB = 1024
		MB = 1024 * KB
	)
	switch {
	case bytes >= MB:
		return fmt.Sprintf("%.1f MB", float64(bytes)/float64(MB))
	case bytes >= KB:
		return fmt.Sprintf("%.1f KB", float64(bytes)/float64(KB))
	default:
		return fmt.Sprintf("%d bytes", bytes)
	}
}
