stages:
  - test

unit-tests:
  stage: test
  image: golang:1.26-bookworm
  script:
    - cd cmd/plgo && go test -v ./...

integration-tests:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t plgo-test .
    - docker run --rm plgo-test
